# Generated by Django 5.0.3 on 2024-07-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='pos_admin.adminuser'),
        ),
    ]
