# Generated by Django 5.0.3 on 2024-07-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_admin', '0002_emaillog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='email_template',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='message_body',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='personalization_tags',
        ),
    ]
