# Generated by Django 5.0.3 on 2024-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_admin', '0003_remove_emaillog_email_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='email_template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='personalization_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
