# Generated by Django 3.2.25 on 2024-07-05 18:58

import django.core.validators
from django.db import migrations, models
import pos_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_admin', '0004_emaillog_email_template_emaillog_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone_number',
            field=models.CharField(max_length=20, validators=[pos_admin.models.validate_phone_number_length]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z ]+$')]),
        ),
    ]
