# Generated by Django 3.2.25 on 2024-07-20 05:27

import django.core.validators
from django.db import migrations, models
import pos_admin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pos_admin', '0005_auto_20240705_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Only alphabetic characters are allowed.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[pos_admin.validators.validate_phone_number_length]),
        ),
    ]
