# Generated by Django 5.0.3 on 2024-06-21 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefPartyType',
            fields=[
                ('party_type_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_enabled', models.CharField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ref_party_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_ref_party_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefPartyProfile',
            fields=[
                ('party_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('ntn_no', models.CharField(max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('payment_terms', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ref_party_profile', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_ref_party_profile', to=settings.AUTH_USER_MODEL)),
                ('ref_party_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_profile', to='pos.refpartytype')),
            ],
        ),
        migrations.CreateModel(
            name='RefVoucherType',
            fields=[
                ('voucher_type_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_enabled', models.CharField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ref_voucher_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_ref_voucher_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockInHand',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('sale_price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('stock_in_hand', models.IntegerField(default=0, null=True)),
                ('order_threshold', models.CharField(max_length=18, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_in_hand', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_in_hand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchaseMain',
            fields=[
                ('bill_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Bill_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_purchase_main', to=settings.AUTH_USER_MODEL)),
                ('ref_party_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchase_main', to='pos.refpartyprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_purchase_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('stock_in_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchase_detail', to='pos.stockinhand')),
                ('stock_purchase_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail', to='pos.stockpurchasemain')),
            ],
        ),
        migrations.CreateModel(
            name='StockSaleMain',
            fields=[
                ('invoice_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_sale_main', to=settings.AUTH_USER_MODEL)),
                ('ref_party_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sale_main', to='pos.refpartyprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_sale_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('stock_in_hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sale_detail', to='pos.stockinhand')),
                ('stock_sale_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='pos.stocksalemain')),
            ],
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('stock_type_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_enabled', models.CharField(max_length=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stock_type', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stock_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='stock_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_hand', to='pos.stocktype'),
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_hand', to='pos.units'),
        ),
    ]
